### ISSUE TITLE
Config flag to avoid setting PTZ constantly

### ISSUE THREAD

**Issue by RomanRobotnik** [RobotnikAutomation/axis_camera#6]
The PTZ node is setting the desired Pan Tilt Zoom values constantly if the param ptz_syncronize is active.

We should change the functionality of this flag in the following way:
1- if active, the component will be sending the PTZ values to the camera constantly (as it does now)
2- If disable, the PTZ command will be sent just once.

**Comment by jamendezib** [comment]
Done in this commit in branch noetic-devel:
https://github.com/RobotnikAutomation/axis_camera/commit/7929515f07851b7532a2a477a002f75e2a599f99

**Comment by rafa-martin** [comment]
Should we implement this feature in previous distros like melodic?

**Comment by jamendezib** [comment]
The branch noetic-devel should work in melodic too. I would have to test it, but it should.
