### ISSUE TITLE
Split PTZ control from Image stream

### ISSUE THREAD

**Issue by RomanRobotnik** [RobotnikAutomation/axis_camera#7]
# Description

Right now there are two classes for controlling the ptz and for streaming the video.
Both in the same file.

# TODO

Split the classes into different files. The classes have to be designed to be used independently from the ROS version.
Split the execution into different nodes
Split the ROS parameters
Try to keep publishing the status and subscribing to the command topics under the same / current namespace.

**Comment by jamendezib** [comment]
Done a first version in branch feat/split-nodes: https://github.com/RobotnikAutomation/axis_camera/tree/feat/split-nodes
It should work both in noetic and melodic.

**Comment by jamendezib** [comment]
Finished in commit https://github.com/RobotnikAutomation/axis_camera/commit/3d3196116c9bb37acad96286e451577936600566
