### ISSUE TITLE
Test and validate Axis P5676-LE

### ISSUE THREAD

**Issue by RomanRobotnik** [RobotnikAutomation/axis_camera#9]
# Description

Test the branch feat/split-nodes with this [new model](https://www.axis.com/products/axis-p5676-le)
Create a new urdf model in robotnik_sensors (we should add a fake joint for the zoom)

# How to validate
- Check the functionality of the camera onboard GUI
- Check the ROS video stream
- Check the Pan-Tilt-Zoom control and the correct joints / TF representation in the model
- Add new model into robotnik_sensors with the zoom joint
- Edit the rest of modes to add the zoom joint
- Update robot_bringup launch and config in order to work with the new component
- PR and merge into master branch

**Comment by RomanRobotnik** [comment]
# Description


Test the branch feat/split-nodes with this [new model](https://www.axis.com/products/axis-p5676-le)
Create a new urdf model in robotnik_sensors (we should add a fake joint for the zoom)

# How to validate
- Check the functionality of the camera onboard GUI
- Check the ROS video stream
- Check the Pan-Tilt-Zoom control and the correct joints / TF representation in the model

**Comment by RomanRobotnik** [comment]
Actualizamos "how to validate"

**Comment by jamendezib** [comment]
Done!

Commit in robot_packages: https://github.com/RobotnikAutomation/robot_packages/commit/375619e850f1c67fb8c27e375ce73dfb073ad2f8
